"""init schema

Revision ID: 4ceff1eb7777
Revises: 
Create Date: 2026-06-27 11:58:34.052783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '4ceff1eb7777'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 启用 pgvector 扩展（幂等，env.py 已执行一次，此处保险）
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_destination'), 'knowledge_entries', ['destination'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_type'), 'knowledge_entries', ['type'], unique=False)
    op.create_table('knowledge_generation_tasks',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_generation_tasks_destination'), 'knowledge_generation_tasks', ['destination'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('conversations',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('travel_plans',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('days_plan', sa.JSON(), nullable=True),
    sa.Column('luggage', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_plans_user_id'), 'travel_plans', ['user_id'], unique=False)
    # ### 手动补充的索引（autogenerate 无法识别 pgvector ivfflat 与组合索引） ###

    # ivfflat 向量索引：知识库语义检索核心索引（cosine 相似度）
    op.execute(
        "CREATE INDEX idx_ke_embedding ON knowledge_entries "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    # 组合索引：按目的地 + 类型过滤知识库（常见查询模式）
    op.create_index("idx_ke_dest_type", "knowledge_entries", ["destination", "type"])
    # 组合索引：会话列表按用户 + 更新时间排序
    op.create_index("idx_conv_user_updated", "conversations", ["user_id", "updated_at"])
    # 组合索引：消息按会话 + id 升序加载历史
    op.create_index("idx_msg_conv_id", "messages", ["conversation_id", "id"])
    # 组合索引：行程列表按用户 + 创建时间排序
    op.create_index("idx_tp_user_created", "travel_plans", ["user_id", "created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### 手动补充索引的删除（先删索引再删表） ###
    op.drop_index("idx_tp_user_created", table_name="travel_plans")
    op.drop_index("idx_msg_conv_id", table_name="messages")
    op.drop_index("idx_conv_user_updated", table_name="conversations")
    op.drop_index("idx_ke_dest_type", table_name="knowledge_entries")
    op.execute("DROP INDEX IF EXISTS idx_ke_embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_plans_user_id'), table_name='travel_plans')
    op.drop_table('travel_plans')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_generation_tasks_destination'), table_name='knowledge_generation_tasks')
    op.drop_table('knowledge_generation_tasks')
    op.drop_index(op.f('ix_knowledge_entries_type'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_destination'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
