"""add user role/active and knowledge owner

Revision ID: 9a11aba01b42
Revises: 4ceff1eb7777
Create Date: 2026-06-27 15:30:02.419641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a11aba01b42'
down_revision: Union[str, Sequence[str], None] = '4ceff1eb7777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：已移除 autogenerate 误判的 5 处 drop_index（idx_conv_user_updated /
    # idx_ke_dest_type / idx_ke_embedding / idx_msg_conv_id / idx_tp_user_created），
    # 这些索引在 init_schema 中手动创建（含 ivfflat 向量索引），不可删除。
    op.add_column('knowledge_entries', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_entries_owner_id'), 'knowledge_entries', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_entries', 'users', ['owner_id'], ['id'])
    op.add_column('knowledge_generation_tasks', sa.Column('triggered_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_generation_tasks_triggered_by'), 'knowledge_generation_tasks', ['triggered_by'], unique=False)
    op.create_foreign_key(None, 'knowledge_generation_tasks', 'users', ['triggered_by'], ['id'])
    # 为已有数据的 users 表添加 NOT NULL 列需提供 server_default
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=sa.text("'user'")))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：已移除 5 处 create_index（idx_tp_user_created / idx_msg_conv_id /
    # idx_ke_embedding / idx_ke_dest_type / idx_conv_user_updated），这些索引
    # 在 init_schema 的 downgrade 中已处理，无需重复创建。
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'knowledge_generation_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_generation_tasks_triggered_by'), table_name='knowledge_generation_tasks')
    op.drop_column('knowledge_generation_tasks', 'triggered_by')
    op.drop_constraint(None, 'knowledge_entries', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_entries_owner_id'), table_name='knowledge_entries')
    op.drop_column('knowledge_entries', 'owner_id')
    # ### end Alembic commands ###
