"""add conversation pending params

Revision ID: fc7934edde6d
Revises: 359ccc1432fa
Create Date: 2026-06-28 00:32:54.361667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7934edde6d'
down_revision: Union[str, Sequence[str], None] = '359ccc1432fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pending_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pending_params')
    # ### end Alembic commands ###
